[package]
name = "crawler"
version = "0.1.0"
authors = ["Philipp Muens <raute1337@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
chrono = "0.4"
reqwest = "0.9.22"
